### ISSUE TITLE
Automated integration tests

### ISSUE THREAD

**Issue by sestrella** [stackbuilders/openssh-github-keys#11]
The usage of `openssh-github-keys` on production environments is sensitive. We need to replicate a production like server using a VM or Docker and configure the SSH daemon with `openssh-github-keys`. That way we could safety test `openssh-github-keys` with `openssh`. There are different approaches for testing this library:

1. Testing with vagrant and virtualbox - Setup a VM, build openssh-github-keys, install openssh-server, configure openssh to get the keys through openssh-github-keys, and finally SSH from the host machine (pros: easy to setup, cons: difficult to test it on Travis).
1. Testing with Docker - Setup a Docker container, install openssh-server, configure openssh to get the keys through openssh-github-keys, and finally SSH from the host machine (pros: Travis provides support for Docker out of the box).
1. Build an Ansible Galaxy that setup and configure openssh-github-keys with openssh-server, and perform an integration tests.

**Comment by sestrella** [comment]
@jsl, @lpaulmp, @mrkkrp, @goetzc any comments?

**Comment by Centeno448** [comment]
Closing since library is being deprecated.
