### ISSUE TITLE
Anyone Please Help Me How Fix this Issue rescue-ssh.target is a disabled or a static unit, not starting it 

### ISSUE THREAD

**Issue by Dark-Project** [stackbuilders/openssh-github-keys#13]
*uname -a
Linux xxxxxx 4.18.0-kali1-amd64 #1 SMP Debian 4.18.6-1kali1 (2018-09-10) x86_64 GNU/Linux

*apt list openssh-server -a
Listing... Done
openssh-server/kali-rolling,now 1:7.8p1-1 amd64 [installed]
openssh-server/kali-current 1:6.7p1-5 amd64

openssh-server/kali-rolling 1:7.8p1-1 i386
openssh-server/kali-current 1:6.7p1-5 i386

*chkconfig -l ssh
ssh                       0:off  1:off  2:on   3:on   4:on   5:on   6:off

*systemctl status ssh.service
● ssh.service - OpenBSD Secure Shell server
   Loaded: loaded (/lib/systemd/system/ssh.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2018-10-16 13:02:30 WIB; 2min 0s ago
     Docs: man:sshd(8)
           man:sshd_config(5)
 Main PID: 5194 (sshd)
    Tasks: 1 (limit: 4915)
   Memory: 1.1M
   CGroup: /system.slice/ssh.service
           └─5194 /usr/sbin/sshd -D

*dpkg-reconfigure openssh-server
Creating SSH2 RSA key; this may take some time ...
2048 SHA256:e4OcOhxIa+B7QxDCM11LfkDdE/iU2MwSPYK2dm7npkg root@SubNetSystem (RSA)
Creating SSH2 ECDSA key; this may take some time ...
256 SHA256:ABo5yaVcpeCD2T6FHteARRbhQAVYKjMTAE+2PdCFWiM root@SubNetSystem (ECDSA)
Creating SSH2 ED25519 key; this may take some time ...
256 SHA256:tYtFtuFbXwhXcG5WpxgP62MLTrEhb7T4nPW53ho8fnM root@SubNetSystem (ED25519)
**rescue-ssh.target is a disabled or a static unit, not starting it.**

*systemctl cat sshd.service
# /lib/systemd/system/ssh.service
[Unit]
Description=OpenBSD Secure Shell server
Documentation=man:sshd(8) man:sshd_config(5)
After=network.target auditd.service
**ConditionPathExists=!/etc/ssh/sshd_not_to_be_run**

[Service]
EnvironmentFile=-/etc/default/ssh
ExecStartPre=/usr/sbin/sshd -t
ExecStart=/usr/sbin/sshd -D $SSHD_OPTS
ExecReload=/usr/sbin/sshd -t
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=on-failure
RestartPreventExitStatus=255
Type=notify
RuntimeDirectory=sshd
RuntimeDirectoryMode=0755

[Install]
WantedBy=multi-user.target
Alias=sshd.service

*sudo systemctl enable ssh.service
Synchronizing state of ssh.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable ssh

Note : Please correct it if there is a mistake in running it, I really appreciate any suggestions and
I am a little hesitant about the Setup Patch SSHD Config that I have, please guide the original SSHD default setup

**Comment by juanpaucar** [comment]
Hi @Dark-Project, this issue doesn't seem related to this package. So I'm closing it.

**Comment by juanpaucar** [comment]
Probably https://unix.stackexchange.com/ or https://www.linuxquestions.org/ might help with your issue
