### ISSUE TITLE
Make it production ready

### ISSUE THREAD

**Issue by sestrella** [stackbuilders/openssh-github-keys#9]
This project still flagged as experimental. In order to make it production ready I think we need to make it error tolerant. I think there are different approaches that we could discuss:

1. Add the ability to configure a fault SSH public key whenever the call to the GitHub API fail.
2. Cache public SSH keys fetched from GitHub API. That way if the call to the API fail we could use the cached ones. However adding an expiration time for the cache would be important as well.

**Comment by Centeno448** [comment]
Closing since library is being deprecated.
